consul-microplatform:
  image: consul
  ports:
    - "8500:8500"
    - "8600:8600/udp"
  volumes:
    - ".volumes/config/:/consul/config" #persisted state. Not used in development mode
    - ".volumes/data/:/consul/data"
  command: consul agent -dev -ui -client 0.0.0.0
