
consul-server:
  image: consul:0.7.5
  hostname: consul-server
  container_name: consul-server
  ports:
   - "8301:8300"
   - "8401:8400"
   - "8501:8500"
   - "8601:8600"
   - "9001:9001"
  volumes:
    - ".volumes/config/:/consul/config" #persisted state. Not used in development mode
    - ".volumes/data/:/consul/data"
  command: consul agent -server -data-dir /consul/data/server -ui -bootstrap-expect 1 -client 0.0.0.0

consul-agent-1:
  image: consul:0.7.5
  hostname: consul-agent-1
  container_name: consul-agent-1
  links:
   - consul-server
  ports:
   - "8302:8300"
   - "8402:8400"
   - "8502:8500"
   - "8602:8600"
   - "9002:9001"
  volumes:
      - ".volumes/data/:/consul/data"
  command: consul agent -data-dir /consul/data/agent-1 -join consul-server

consul-agent-2:
  image: consul:0.7.5
  hostname: consul-agent-2
  container_name: consul-agent-2
  links:
   - consul-server
  ports:
   - "8303:8300"
   - "8403:8400"
   - "8503:8500"
   - "8603:8600"
   - "9003:9001"
  volumes:
      - ".volumes/data/:/consul/data"
  command: consul agent -data-dir /consul/data/agent-2 -join consul-server
